pluginManagement {
    repositories {
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.neoforged.net/releases" }
        maven { url "https://maven.fabricmc.net/" }
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

include 'common', 'fabric', 'neoforge'

gradle.beforeProject { project ->
    project.group = settings.mod_group_id
    project.version = settings.mod_version
}
